name: base

on:
  schedule:
    - cron: '0 15 * * *'
  pull_request:
    paths:
      - './**'
      - '.github/workflows/base.yml'

jobs:
  examples:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: setup-python${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install (Python)
      run: |
        python -m pip install --upgrade pip
        pip install --progress-bar off -U setuptools
        pip install git+https://github.com/optuna/optuna.git
        python -c 'import optuna'

        pip install -r requirements.txt
        # TODO(crissman): resolve cudf issues for rapids
        # conda install -c rapidsai -c nvidia -c conda-forge rapids-blazing
    - name: Run examples
      run: |
        python max_trials_callback.py
        python enqueue_trial.py
        python quadratic_simple.py
        python simple_pruning.py
        python skimage/skimage_lbp_simple.py
        # python ray/ray_joblib.py
        # python rapids_simple.py
      env:
        OMP_NUM_THREADS: 1
